---
- name: Test playbook
  hosts: localhost
  connection: local
  vars:
    ansible_python_interpreter: /usr/bin/python3.12
  tasks:
    - name: Print a message
      debug:
        msg: "Ansible is Working!"
