name: CI-CD

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKER_USER }}/sre-app:${{ github.sha }} .

      - name: Login DockerHub
        run: echo "${{ secrets.DOCKER_PASS }}" | docker login -u ${{ secrets.DOCKER_USER }} --password-stdin

      - name: Push image
        run: docker push ${{ secrets.DOCKER_USER }}/sre-app:${{ github.sha }}